# Notas, reseñas y memos

Por alguna razón suele considerarse a la escritura como la etapa final
de una investigación. Lees, investigas y por último escribes. Parece muy
razonable, pero en realidad leemos en cualquier día y tenemos ideas a
cualquier hora. No tendríamos que esperar hasta el final para
escribirlas. Ideas surgen en todo lugar y en todo momento. Seguramente
has tenido destellos de creatividad que quedaron en tu propio olvido por
no anotarlas. Por eso son importantes las notas. Un paso para
materializar tus ideas es escribir sobre ellas. No importa la extensión
o el contenido, lo importante es escribir. Anota tus impresiones sobre
un documental, sobre una exposición, haz notas sobre una idea o sobre lo
que sea. En este apartado quiero delinear algunos consejos sobre la
escritura de notas, memos y pequeñas reseñas, resaltando también algunas
de sus virtudes que pueden ser de utilidad.

## Notas


No hay forma correcta de hacer notas. Algunos toman notas caóticas y aun
así son capaces de darles gran orden en la etapa final de escritura.
Otros pueden ser muy metódicos, tener un sistema altamente organizado y
sin embargo utilizar sus notas de forma inadecuada. Cada persona
desarrolla su propio flujo de trabajo, pero lo importante es que
funcione y no solo sea una actividad pasiva carente de utilidad. No creo
que sea tan importante como las llames o cómo las hagas, pero sí
diferenciar la naturaleza de tus anotaciones para que después puedas
trabajar con ellas de mejor forma.

Cuando hablo de notas no me refiero a notas de clase, sino notas en
general: anotaciones fugaces, párrafos pequeños u oraciones atómicas que
después se van desarrollando. Las notas son micro y medianos escritos
sobre prácticamente cualquier cosa que quieras mantener en el tiempo.
Son oraciones y párrafos con potencial creativo con el objetivo de ser
utilizados más adelante. Las notas no sólo son el registro de tu
pensamiento, pueden pensarse incluso como tu propio pensamiento. Yo sé
que puede parecer absurdo, pero realmente hay quienes lo defienden
(Ahrens, 2017; Luhmann, 1981). Escribir notas es un ejercicio constante
para la cristalización de tus ideas. Las notas son la materialización de
tu pensamiento que puedes recuperar más adelante cuando lo necesites.
Otra de sus virtudes está en la escritura. Escribir puede ser una tarea
muy pesadaen cambio escribir pequeñas anotaciones puede ser muy ligero,
y sin embargo, cumple con los mismos objetivos. Tus notas/ideas se van
agregando con el tiempo y al final tendrás una gran cantidad de
productos que has ido desarrollando en un proceso continuo de escritura.
Tendrás que dar orden, pero las ideas ya están ahí. Si no logré
transmitir la importancia de las notas, tal vez Lévi-Strauss pueda
hacerlo:

> But I get by when I work by accumulating notes - a bit about
> everything, ideas captured on the fly, summaries of what I have read,
> references, quotations\... And when I want to start a project, I pull
> a packet of notes out of their pigeonhole and deal them out like a
> deck of cards. This kind of operation, where chance plays a role,
> helps me revive my failing memory... (Lévi-Strauss citado por Kil,
> 2017: 96)

## Tipos de notas


Sin pensarlo, como estudiantes estamos haciendo notas de todo tipo. Tal
vez no sea importante detenerse en tipologías y caracterizaciones, pero
puede servir conocer algunas propuestas para acercarnos a la comprensión
de qué hacemos y qué podemos hacer. Aquí sintetizo algunos tipos que
considero importantes para el trabajo académico.[^9]

-   Anotaciones rápidas: Es una anotación *temporal* realizada en el
    momento para captar una idea o información que se utiliza para
    después redactar una nota más amplia. Los *joints* en el trabajo de
    campo son un buen ejemplo.
-   Notas sintéticas: Pequeños escritos sobre ideas propias que pueden
    ayudar a la escritura posterior. Las notas sintéticas pueden
    convertirse en notas permanentes con contenido más desarrollado.
-   Notas de lectura: Se resume el contenido de algún texto con su
    respectiva referencia. De tus notas de lectura pueden hacerse
    pequeñas reseñas.
-   Notas permanentes: Contienen una o varias ideas desarrolladas,
    explicadas y bien redactadas producto de otras pequeñas notas. Con
    estas notas podrás trabajar y redactar productos finales.
-   Memos: Los memos registran las ideas analíticas de nuestras
    observaciones y nuestro proceso de trabajo para después utilizarlas
    como material de trabajo. Aquí se incluyen hipótesis, posibles
    explicaciones, conexiones conceptuales o análisis de datos que vayan
    surgiendo en el camino.
-   Notas de proyecto: Ayudan a gestionar un proyecto que estés
    realizando, se incluyen indicaciones, objetivos y tareas restantes.

La idea es que éstas se integren a nuestro trabajo a largo plazo y no
solo unos cuantos meses. Para eso también sirve redactar notas
permanentes y memos, que ya son un avance importante de síntesis y
análisis. Pienso que *los memos y las notas de lectura son de particular
importancia,* por eso el siguiente apartado.

## Reseñas y memos

Me atrevería a decir que una lectura sin subrayados y sin notas no es
una buena lectura. Esto es simplemente porque la lectura de un texto
implica una reflexión paralela. Si ya leíste un texto, por lo menos
trata de sacar lo más importante de ahí. Conceptos, ideas, citas
importantes. Generalmente eso se hace subrayando, pero lo ideal es que
también entrenes tu redacción y capacidad de síntesis reescribiendo las
ideas del texto. No tiene que ser algo muy grande, un párrafo o dos
puede ser suficiente. Felicidades, ya hiciste una reseña.[^10] Pero tú
también tienes ideas sobre el texto, eso también es importante anotarlo.
Haz notas pequeñas, después esas notas se harán más grandes y las ideas
crecerán para hacer memos. Los memos son esas anotaciones que acompañan
tu pensamiento y proceso de trabajo. Pueden ser sobre textos, videos,
archivos, fotos o tu proceso de escritura, el desarrollo de un trabajo,
lo que sea. Los memos son registros de tu pensamiento analítico (Corbin
& Strauss, 2015).

> Memo-writing allows you to really engage with the material (beyond
> highlighting and taking notes on the margins of your printed copies,
> or digital ones in PDF). Writing memoranda also allows you to
> integrate reading into your writing workflow. Stuck in the morning
> during your alloted writing time? You can read an article and write a
> memorandum about it = problem solved. You can write memos about your
> readings, about your fieldwork, about your data (laboratory or field
> or computer-generated). The key element is that whatever kind of memo
> you write, it should be useful to you (Pacheco-Vega, 2016).

Tus reseñas sintetizan tu lectura sobre un texto, así no tienes que
regresar al texto cada vez que tengas dudas al respecto. Tus subrayados
se condensan en oraciones redactadas por ti y no es necesario releer
párrafos enteros desconectados del contexto literario. Por otro lado tus
memos acompañan la lectura con tus ideas que fueron surgiendo a la par.
De tus reseñas surgen nuevos memos y de tus memos surgen nuevas ideas
que luego se hacen notas. Las reseñas y memos están subestimadas. En
serio pueden ser de gran ayuda en la escritura de trabajos, ensayos,
presentaciones o lo que sea que venga en el futuro. Los memos y las
reseñas forman parte de tu archivo que puedes ocupar más adelante. *Los
memos pueden convertirse en ensayos y las reseñas en marcos teóricos**.*

## Almacenamiento de notas {#almacenamiento-de-notas-1}


*Las notas deben ser legibles y consultables en el tiempo*. No sé a ti,
pero a mí las anotaciones y los rayones en papel se me pierden
fácilmente. Las ideas se pierden, por eso hay que documentarlas de
alguna forma confiable. Hay que plasmarlas. Las anotaciones rápidas al
margen de un texto pueden servir momentáneamente, pero siempre es mejor
redactarlas de mejor manera y moverlas a un espacio duradero para que te
puedan ser de utilidad en el futuro.

Aquí me concentro en formas digitales de tomar notas. Hacer notas
digitales tiene sus ventajas: es más fácil manejarlas y editarlas,
puedes indagar y acceder a ellas de forma más ágil, y, dependiendo del
software que uses, hay grandes funcionalidades para utilizar a tu favor.
Lo primero es usar un programa diseñado especialmente para escribir y
guardar notas[^11]. Joplin, Evernote, Notion o OneNote son algunas
opciones que podrías revisar, aunque hay muchas más[^12]. *Ninguna
opción es perfecta*, lo mejor es probarlas y que las evalúes de acuerdo
con tus necesidades. Casi todas las opciones tienen características
similares, pero hay diferenciadores entre ellas: *Evernote* es muy
popular para etiquetar notas y contenido multimedia además de que
formatea texto; *Notion* tiene características similares, es muy
maleable y personalizable, puedes ordenar su estructura como quieras y
organizar tu información en diferentes plantillas; *Joplin* es una
opción libre y de código abierto confiable y segura que integra las
ventajas del formato Markdown; *OneNote* forma parte de la ofimática de
Office y puede llamarte la atención su forma de organización por
carpetas, cuadernos y hojas; *DEVONthink* es una opción popular entre
los usuarios de iOS. Existen muchas opciones y existirán más.[^13] En el
siguiente apartado hablaré de otras opciones más complejas que podrían
interesarte para la [gestión del
conocimiento](#gestión-del-conocimiento).

Sea cual sea el software que utilices, éste debería ser lo
suficientemente flexible para manejar y exportar tus archivos cómo
quieras. Imagina que haces todas tus notas en un programa, te decepciona
y después quieres utilizar otro. Un buen programa por lo menos te
dejaría migrar sin peros. Y relacionado con lo anterior está el tipo de
archivo[^14]. El archivo de tus notas tiene que ser a-prueba-de-futuro.
Quieres que tus notas sirvan durante muchos años más.[^15] Por último
solo me queda decir que lo importante es que el software que uses sea
confiable y estable, además de que conozcas lo suficiente sobre él para
sacarle el máximo provecho posible. Que la elección de software no te
distraiga de lo más importante: *escribir*.


# Organización


Es común que el trabajo académico se entienda como un proceso lineal. Se
inicia con una pregunta, se lee al respecto, se investiga y finalmente
se escribe un producto. Lo malo es que el último paso parece nunca
llegar y se perdió mucho tiempo esperándolo. En realidad, el proceso es
más enredado y recursivo. *Mucho del trabajo "final" realmente se
encuentra en los momentos previos*; en tu escritura continua de notas y
memos o en la lectura de tus notas de campo. Para que ese trabajo
constante se mantenga en el tiempo y pueda serte útil para el análisis
posterior es necesario poner cierto orden a toda la información
recogida. Fotos, audios, textos, ideas, memos, reseñas. La organización
es un paso fundamental para eso*.* No importa si eres una persona
caótica o muy dispersa, por lo menos debes tener una idea de cómo están
distribuidos tus datos e información para que te sean útiles a lo largo
de tu trabajo. La organización de la información es de doble
importancia. Primero, tal vez lo principal, porque permite que tu
información, a la que le has invertidos tiempo investigando, leyendo y
escribiendo, *se mantenga útil y disponible en el tiempo*. Y segundo,
porque la organización de tu información requiere indirectamente una
reflexión sobre ella y te ayudará a que el proceso de análisis sea más
fluido. *No desestimes la organización de tu trabajo en su conjunto.*

## Gestión del conocimiento

Conforme el acceso a información ha incrementado, también se han
desarrollado herramientas para gestionar las cada vez más grandes
cantidades de información. Científicos, filósofos, bibliotecólogos y
demás pensadores han jugado un papel importante en dichos desarrollos
que generalmente se dan por tácitos. En lo que a las ciencias sociales
respecta, existen pocos académicos que explicitan su forma de trabajo
(Blair, 2010; Cevolini, 2016; Luhmann, 1981; Mills, 1980), tal vez
porque podría parecer banal y superficial, cuando en realidad se trata
de una cuestión fundamental. Miramos los resultados logrados y no las
herramientas por medio de las cuáles fueron posibles esos grandes
productos. A lo largo de todo este capítulo repleto de consejos
prácticos he buscado dar idea de estas herramientas, que en su conjunto,
pueden acercarse a la explicitación de cómo es el trabajo académico en
los tiempos que escribo. Para este apartado sobre gestión del
conocimiento, recomiendo que se recapitulen algunas de las herramientas
que he descrito brevemente en apartados anteriores para dar una mejor
idea al respecto.

## Aparatos académicos análogos


Por mucho tiempo los archivos, diarios, cajas y fichas fueron *la*
herramienta con las que se realizaba el trabajo académico. Gran parte de
los desarrollos de la gestión del conocimiento antes de los 2000 se
realizaron con estos aparatos. Fichas de papel, un buen bolígrafo,
cajas, ficheros, carpetas, sobres, un escritorio adecuado y una silla
cómoda. Muchos de estos procesos han perdurado, otros se han adaptado,
modificado y otros nuevos han surgido. Actualmente esto puede parecer
obsoleto (pienso que en parte lo es), pero los desarrollos que se
lograron a lo largo de décadas deben servir de algo para la gestión del
conocimiento en tiempos contemporáneos. Grandes antropólogos y
sociólogos trabajaron de esta manera, desde Claude Lévi-Strauss, Roland
Barthes o Niklas Luhmann (a quienes menciono porque su forma de trabajo
está registrada), además de muchísimas personas más, incluyendo a
algunos de tus profesores.[^16] Sería importuno decir en que consistían
estas formas de trabajo dado que están en desuso, pero vale la pena
revisarlas para ver cómo *realmente* trabajaban los y las académicas
(Blair, 2010; Cevolini, 2016; Duda et al., 2017; McGranahan, 2020;
Pandian, 2019) y porque lamentablemente no tengo espacio para
describirlas.

## Guías para la gestión digital del conocimiento


Aquí doy algunas pistas para la gestión del conocimiento en tiempos
digitales donde las principales herramientas son una computadora,
software adecuado y un buen sistema de organización. No me gustaría
decir que hay métodos incondicionales y definitivos, me parece muy
cuadrado. Siempre será mejor la adaptación según tus gustos y
necesidades. Mucho de esto incluso lo haces por puro sentido común, pero
saber que hay gente que lo ha sistematizado da un poco de aliento para
tomar algunas ideas y construir tu propio sistema poco a poco.

En estos años se han desarrollado algunos sistemas populares para el
manejo digital de información. Hay quienes enfatizan la productividad y
el manejo de proyectos (como el método P.A.R.A.), otros más se dedican
al almacenamiento eficaz de contenido multimedia (para gestionar
marcadores en línea), un grupo importante busca manejar notas de la
mejor forma posible (como el del libro de Ahrens y los seguidores de
Luhmann) y algunos buscan dotar a académicos de un sistema coherente de
categorización (como los sistemas decimales y bibliotecológicos). Para
comentarlas rápidamente digamos que hay sistemas basados en el orden y
la estructura mientras que otros son más libres y espontáneos. La
distinción puede remitir a la célebre distinción entre jardineros y
arquitectos de George R. R. Martin, pero en lo que a gestión del
conocimiento se refiere, la oposición podría ser entre *folgezettel* y
*zettelkasten*.[^17] Que los nombres en alemán no te asusten, la
distinción es simple. La primera basa su poder en una estructura de
árbol con categorías bien establecidas, llenando la estructura con la
información correspondiente (similar a si nos guiáramos por la Guía
Murdock para datos culturales) y la otra se basa en el surgimiento de
notas y conexiones entre ellas sin un orden preestablecido.

El método zettelkasten se ha hecho muy popular por haber sido la
elección de Niklas Luhmann para realizar su trabajo.[^18] El método se
basa en la escritura y *almacenamiento* notas de lectura y notas
permanentes estableciendo conexiones entre ellas a través de
identificadores numéricos únicos (Luhmann, 1981; Schmidt, 2016). A pesar
de ser muy antiguo (incluso muy anterior al propio Luhmann), el sistema
se ha recuperado por ser fácilmente adaptable a tiempos digitales por
medio de software. Es un método simple. No se necesitan muchos recursos,
es fácilmente replicable y al mismo tiempo muy maleable.[^19] Si a eso
se agrega la promesa de ser tan prolífico como Luhmann, el sistema
zettelkasten es más que prometedor. Sin embargo hay que tratarlo con
mucho cuidado. El sistema no es la panacea del trabajo académico y puede
ser una decepción si lo tomamos al pie de la letra. El sistema requiere
ciertas condiciones, cierto tipo de notas y cierto tipo de vínculos. No
todo en tra en el método. De cualquier forma puede servir de inspiración
para implementar nuestro propio sistema, que es lo que deberíamos
perseguir a lo largo del tiempo. Con estas aclaraciones hechas veamos en
que consiste el método.
